// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA-nDzo2JaTXOg8AdKjnZOoR2gaQHw0_4',
    appId: '1:620671048354:web:c986d8b739f9b9e9eb55fb',
    messagingSenderId: '620671048354',
    projectId: 'drugreport-87e04',
    authDomain: 'drugreport-87e04.firebaseapp.com',
    storageBucket: 'drugreport-87e04.firebasestorage.app',
    measurementId: 'G-YW8BWTSP6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHo-zFOqe5O-84NxMbEYnCbc7mF3wqdSU',
    appId: '1:620671048354:android:109dab6bf2c57629eb55fb',
    messagingSenderId: '620671048354',
    projectId: 'drugreport-87e04',
    storageBucket: 'drugreport-87e04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIWBPVweLnAkqKSuVlrzgRwXr2QSKiGp4',
    appId: '1:620671048354:ios:046110321cf7536feb55fb',
    messagingSenderId: '620671048354',
    projectId: 'drugreport-87e04',
    storageBucket: 'drugreport-87e04.firebasestorage.app',
    iosBundleId: 'com.example.drugreport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIWBPVweLnAkqKSuVlrzgRwXr2QSKiGp4',
    appId: '1:620671048354:ios:046110321cf7536feb55fb',
    messagingSenderId: '620671048354',
    projectId: 'drugreport-87e04',
    storageBucket: 'drugreport-87e04.firebasestorage.app',
    iosBundleId: 'com.example.drugreport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA-nDzo2JaTXOg8AdKjnZOoR2gaQHw0_4',
    appId: '1:620671048354:web:11b1f92d3e17ad6deb55fb',
    messagingSenderId: '620671048354',
    projectId: 'drugreport-87e04',
    authDomain: 'drugreport-87e04.firebaseapp.com',
    storageBucket: 'drugreport-87e04.firebasestorage.app',
    measurementId: 'G-W48TXSNVJJ',
  );
}
